version: '3.8'

services:
  web:
    build:
      context: ./backend
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./backend:/usr/src/app
      - ./uploads:/usr/src/app/uploads
    command: go run cmd/main.go -b 0.0.0.0

  db:
    image: postgres:alpine3.19
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=courseWork
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres-db:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start

volumes:
  postgres-db:
